### ISSUE TITLE
Update ers-dbwriter to use ERSStreamer

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/microservices#53]

**Comment by jcpunk** [comment]
Long term I wonder if it might be better to use Kafka Connect to stream from Kafka to PostgreSQL?

It might be easier to use the `telegraf` Kafka input and postgresql output, but I think that might change the table name thus impacting the dashboards.  I have no idea how to test that as I'm unsure what the kafka messages should actually look like.... Is there a sample message generator I could play with?

**Comment by mroda88** [comment]
Hi Pat, I think that goes in the wrong direction. If the desired design is adding layer between kafka and our code so that we become independent from the broker technology, using KafkaConnect breaks the logic as we will tie ourselves even strongly to kafka. 

The change in the table name is not an issues, we have the control over all the elements of the chain, so that would not be an issue. In fact we are planning to change the table name with the new stream. 

About message generation, I have written a few to test the ERSPublisher, you can probably use this: https://github.com/DUNE-DAQ/erskafka/blob/develop/test/apps/protobuf_stream_test.cxx just create and environment and call `protobuf_stream_test` and you will send messages. You can test them with kafka_spy or with https://github.com/DUNE-DAQ/erskafka/blob/develop/test/scripts/ers_subscriber_test

**Comment by jcpunk** [comment]
Do you think the `telegraf` bridge might work?  I don't have enough infrastructure in place to really even test it, let alone evaluate if it actually works rationally...

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kafka_consumer
https://github.com/influxdata/telegraf/tree/master/plugins/outputs/postgresql

**Comment by mroda88** [comment]
We can make it work for sure but, to do so, we have to forsake the ERSSubscriber, and again it goes against the logic of the independence from the broker technology. I think we should add these points in the technology evaluations though. I was hoping to start with you as soon as we finish the business of the release.

**Comment by TiagoTAlves** [comment]
Pat tried telegraf but due to particular logic of the entries this cannot be done and the microservice is the only alternative solution
