### ISSUE TITLE
Config Service no longer in use (I think)

### ISSUE THREAD

**Issue by TiagoTAlves** [DUNE-DAQ/microservices#95]
We are no longer using MongoDB for the configuration service (or the config service at all I believe)

**Comment by plasorak** [comment]
I think it should definitely not be deployed, whether we delete the yaml is another question.

**Comment by TiagoTAlves** [comment]
Discuss at CCM?

**Comment by TiagoTAlves** [comment]
Closed after conversation at CCM today
